/** @format */

// src/features/game/sprites/jrtSpriteManifest.js
// Loads a manifest generated by scripts/build-sprite-strips-from-frames.js
// This lets you add REAL animations without touching code.

import { withBaseUrl } from "@/utils/assetUrl.js";

let _manifestPromise = null;

export function loadJrtManifest() {
  if (_manifestPromise) return _manifestPromise;

  const url = withBaseUrl(`/sprites/anim/jrt/manifest.json?ts=${Date.now()}`);
  _manifestPromise = fetch(url)
    .then((r) => {
      if (!r.ok) throw new Error(`manifest fetch failed: ${r.status}`);
      return r.json();
    })
    .catch(() => null);

  return _manifestPromise;
}
