/** @format */

// Auto-generated asset list for Jack Russell frames + animations.
// Generated from public/assets/atlas/jr_*.json/png.

import { withBaseUrl } from "@/utils/assetUrl.js";

const FRAME_BASE = "/assets/frames/jr";
const toUrl = (file) => withBaseUrl(`${FRAME_BASE}/${file}`);

export const JACK_RUSSELL_FRAME_URLS = [
  toUrl("jr_adult_clean_normal_neutral_bark_00.png"),
  toUrl("jr_adult_clean_normal_neutral_bark_01.png"),
  toUrl("jr_adult_clean_normal_neutral_bark_02.png"),
  toUrl("jr_adult_clean_normal_neutral_bark_03.png"),
  toUrl("jr_adult_clean_normal_neutral_idle_00.png"),
  toUrl("jr_adult_clean_normal_neutral_idle_01.png"),
  toUrl("jr_adult_clean_normal_neutral_idle_02.png"),
  toUrl("jr_adult_clean_normal_neutral_idle_03.png"),
  toUrl("jr_adult_clean_normal_neutral_idle_04.png"),
  toUrl("jr_adult_clean_normal_neutral_idle_05.png"),
  toUrl("jr_adult_clean_normal_neutral_scratch_00.png"),
  toUrl("jr_adult_clean_normal_neutral_scratch_01.png"),
  toUrl("jr_adult_clean_normal_neutral_scratch_02.png"),
  toUrl("jr_adult_clean_normal_neutral_scratch_03.png"),
  toUrl("jr_adult_clean_normal_neutral_scratch_04.png"),
  toUrl("jr_adult_clean_normal_neutral_scratch_05.png"),
  toUrl("jr_adult_clean_normal_neutral_shake_00.png"),
  toUrl("jr_adult_clean_normal_neutral_shake_01.png"),
  toUrl("jr_adult_clean_normal_neutral_shake_02.png"),
  toUrl("jr_adult_clean_normal_neutral_shake_03.png"),
  toUrl("jr_adult_clean_normal_neutral_shake_04.png"),
  toUrl("jr_adult_clean_normal_neutral_shake_05.png"),
  toUrl("jr_adult_clean_normal_neutral_sit_00.png"),
  toUrl("jr_adult_clean_normal_neutral_sit_01.png"),
  toUrl("jr_adult_clean_normal_neutral_sit_02.png"),
  toUrl("jr_adult_clean_normal_neutral_sit_03.png"),
  toUrl("jr_adult_clean_normal_neutral_sleep_00.png"),
  toUrl("jr_adult_clean_normal_neutral_sleep_01.png"),
  toUrl("jr_adult_clean_normal_neutral_sleep_02.png"),
  toUrl("jr_adult_clean_normal_neutral_sleep_03.png"),
  toUrl("jr_adult_clean_normal_neutral_sleep_04.png"),
  toUrl("jr_adult_clean_normal_neutral_sleep_05.png"),
  toUrl("jr_adult_clean_normal_neutral_stay_00.png"),
  toUrl("jr_adult_clean_normal_neutral_stay_01.png"),
  toUrl("jr_adult_clean_normal_neutral_stay_02.png"),
  toUrl("jr_adult_clean_normal_neutral_stay_03.png"),
  toUrl("jr_adult_clean_normal_neutral_walk_00.png"),
  toUrl("jr_adult_clean_normal_neutral_walk_01.png"),
  toUrl("jr_adult_clean_normal_neutral_walk_02.png"),
  toUrl("jr_adult_clean_normal_neutral_walk_03.png"),
  toUrl("jr_adult_clean_normal_neutral_walk_04.png"),
  toUrl("jr_adult_clean_normal_neutral_walk_05.png"),
  toUrl("jr_adult_clean_normal_neutral_walk_06.png"),
  toUrl("jr_adult_clean_normal_neutral_walk_07.png"),
  toUrl("jr_pup_clean_normal_neutral_bark_00.png"),
  toUrl("jr_pup_clean_normal_neutral_bark_01.png"),
  toUrl("jr_pup_clean_normal_neutral_bark_02.png"),
  toUrl("jr_pup_clean_normal_neutral_bark_03.png"),
  toUrl("jr_pup_clean_normal_neutral_idle_00.png"),
  toUrl("jr_pup_clean_normal_neutral_idle_01.png"),
  toUrl("jr_pup_clean_normal_neutral_idle_02.png"),
  toUrl("jr_pup_clean_normal_neutral_idle_03.png"),
  toUrl("jr_pup_clean_normal_neutral_idle_04.png"),
  toUrl("jr_pup_clean_normal_neutral_idle_05.png"),
  toUrl("jr_pup_clean_normal_neutral_scratch_00.png"),
  toUrl("jr_pup_clean_normal_neutral_scratch_01.png"),
  toUrl("jr_pup_clean_normal_neutral_scratch_02.png"),
  toUrl("jr_pup_clean_normal_neutral_scratch_03.png"),
  toUrl("jr_pup_clean_normal_neutral_scratch_04.png"),
  toUrl("jr_pup_clean_normal_neutral_scratch_05.png"),
  toUrl("jr_pup_clean_normal_neutral_shake_00.png"),
  toUrl("jr_pup_clean_normal_neutral_shake_01.png"),
  toUrl("jr_pup_clean_normal_neutral_shake_02.png"),
  toUrl("jr_pup_clean_normal_neutral_shake_03.png"),
  toUrl("jr_pup_clean_normal_neutral_shake_04.png"),
  toUrl("jr_pup_clean_normal_neutral_shake_05.png"),
  toUrl("jr_pup_clean_normal_neutral_sit_00.png"),
  toUrl("jr_pup_clean_normal_neutral_sit_01.png"),
  toUrl("jr_pup_clean_normal_neutral_sit_02.png"),
  toUrl("jr_pup_clean_normal_neutral_sit_03.png"),
  toUrl("jr_pup_clean_normal_neutral_sleep_00.png"),
  toUrl("jr_pup_clean_normal_neutral_sleep_01.png"),
  toUrl("jr_pup_clean_normal_neutral_sleep_02.png"),
  toUrl("jr_pup_clean_normal_neutral_sleep_03.png"),
  toUrl("jr_pup_clean_normal_neutral_sleep_04.png"),
  toUrl("jr_pup_clean_normal_neutral_sleep_05.png"),
  toUrl("jr_pup_clean_normal_neutral_stay_00.png"),
  toUrl("jr_pup_clean_normal_neutral_stay_01.png"),
  toUrl("jr_pup_clean_normal_neutral_stay_02.png"),
  toUrl("jr_pup_clean_normal_neutral_stay_03.png"),
  toUrl("jr_pup_clean_normal_neutral_walk_00.png"),
  toUrl("jr_pup_clean_normal_neutral_walk_01.png"),
  toUrl("jr_pup_clean_normal_neutral_walk_02.png"),
  toUrl("jr_pup_clean_normal_neutral_walk_03.png"),
  toUrl("jr_pup_clean_normal_neutral_walk_04.png"),
  toUrl("jr_pup_clean_normal_neutral_walk_05.png"),
  toUrl("jr_pup_clean_normal_neutral_walk_06.png"),
  toUrl("jr_pup_clean_normal_neutral_walk_07.png"),
  toUrl("jr_senior_clean_normal_neutral_bark_00.png"),
  toUrl("jr_senior_clean_normal_neutral_bark_01.png"),
  toUrl("jr_senior_clean_normal_neutral_bark_02.png"),
  toUrl("jr_senior_clean_normal_neutral_bark_03.png"),
  toUrl("jr_senior_clean_normal_neutral_idle_00.png"),
  toUrl("jr_senior_clean_normal_neutral_idle_01.png"),
  toUrl("jr_senior_clean_normal_neutral_idle_02.png"),
  toUrl("jr_senior_clean_normal_neutral_idle_03.png"),
  toUrl("jr_senior_clean_normal_neutral_idle_04.png"),
  toUrl("jr_senior_clean_normal_neutral_idle_05.png"),
  toUrl("jr_senior_clean_normal_neutral_scratch_00.png"),
  toUrl("jr_senior_clean_normal_neutral_scratch_01.png"),
  toUrl("jr_senior_clean_normal_neutral_scratch_02.png"),
  toUrl("jr_senior_clean_normal_neutral_scratch_03.png"),
  toUrl("jr_senior_clean_normal_neutral_scratch_04.png"),
  toUrl("jr_senior_clean_normal_neutral_scratch_05.png"),
  toUrl("jr_senior_clean_normal_neutral_shake_00.png"),
  toUrl("jr_senior_clean_normal_neutral_shake_01.png"),
  toUrl("jr_senior_clean_normal_neutral_shake_02.png"),
  toUrl("jr_senior_clean_normal_neutral_shake_03.png"),
  toUrl("jr_senior_clean_normal_neutral_shake_04.png"),
  toUrl("jr_senior_clean_normal_neutral_shake_05.png"),
  toUrl("jr_senior_clean_normal_neutral_sit_00.png"),
  toUrl("jr_senior_clean_normal_neutral_sit_01.png"),
  toUrl("jr_senior_clean_normal_neutral_sit_02.png"),
  toUrl("jr_senior_clean_normal_neutral_sit_03.png"),
  toUrl("jr_senior_clean_normal_neutral_sleep_00.png"),
  toUrl("jr_senior_clean_normal_neutral_sleep_01.png"),
  toUrl("jr_senior_clean_normal_neutral_sleep_02.png"),
  toUrl("jr_senior_clean_normal_neutral_sleep_03.png"),
  toUrl("jr_senior_clean_normal_neutral_sleep_04.png"),
  toUrl("jr_senior_clean_normal_neutral_sleep_05.png"),
  toUrl("jr_senior_clean_normal_neutral_stay_00.png"),
  toUrl("jr_senior_clean_normal_neutral_stay_01.png"),
  toUrl("jr_senior_clean_normal_neutral_stay_02.png"),
  toUrl("jr_senior_clean_normal_neutral_stay_03.png"),
  toUrl("jr_senior_clean_normal_neutral_walk_00.png"),
  toUrl("jr_senior_clean_normal_neutral_walk_01.png"),
  toUrl("jr_senior_clean_normal_neutral_walk_02.png"),
  toUrl("jr_senior_clean_normal_neutral_walk_03.png"),
  toUrl("jr_senior_clean_normal_neutral_walk_04.png"),
  toUrl("jr_senior_clean_normal_neutral_walk_05.png"),
  toUrl("jr_senior_clean_normal_neutral_walk_06.png"),
  toUrl("jr_senior_clean_normal_neutral_walk_07.png"),
];

export const JACK_RUSSELL_ANIMATIONS = [
  {
    stage: "pup",
    name: "bark",
    urls: [
      toUrl("jr_pup_clean_normal_neutral_bark_00.png"),
      toUrl("jr_pup_clean_normal_neutral_bark_01.png"),
      toUrl("jr_pup_clean_normal_neutral_bark_02.png"),
      toUrl("jr_pup_clean_normal_neutral_bark_03.png"),
    ],
  },
  {
    stage: "pup",
    name: "idle",
    urls: [
      toUrl("jr_pup_clean_normal_neutral_idle_00.png"),
      toUrl("jr_pup_clean_normal_neutral_idle_01.png"),
      toUrl("jr_pup_clean_normal_neutral_idle_02.png"),
      toUrl("jr_pup_clean_normal_neutral_idle_03.png"),
      toUrl("jr_pup_clean_normal_neutral_idle_04.png"),
      toUrl("jr_pup_clean_normal_neutral_idle_05.png"),
    ],
  },
  {
    stage: "pup",
    name: "scratch",
    urls: [
      toUrl("jr_pup_clean_normal_neutral_scratch_00.png"),
      toUrl("jr_pup_clean_normal_neutral_scratch_01.png"),
      toUrl("jr_pup_clean_normal_neutral_scratch_02.png"),
      toUrl("jr_pup_clean_normal_neutral_scratch_03.png"),
      toUrl("jr_pup_clean_normal_neutral_scratch_04.png"),
      toUrl("jr_pup_clean_normal_neutral_scratch_05.png"),
    ],
  },
  {
    stage: "pup",
    name: "shake",
    urls: [
      toUrl("jr_pup_clean_normal_neutral_shake_00.png"),
      toUrl("jr_pup_clean_normal_neutral_shake_01.png"),
      toUrl("jr_pup_clean_normal_neutral_shake_02.png"),
      toUrl("jr_pup_clean_normal_neutral_shake_03.png"),
      toUrl("jr_pup_clean_normal_neutral_shake_04.png"),
      toUrl("jr_pup_clean_normal_neutral_shake_05.png"),
    ],
  },
  {
    stage: "pup",
    name: "sit",
    urls: [
      toUrl("jr_pup_clean_normal_neutral_sit_00.png"),
      toUrl("jr_pup_clean_normal_neutral_sit_01.png"),
      toUrl("jr_pup_clean_normal_neutral_sit_02.png"),
      toUrl("jr_pup_clean_normal_neutral_sit_03.png"),
    ],
  },
  {
    stage: "pup",
    name: "sleep",
    urls: [
      toUrl("jr_pup_clean_normal_neutral_sleep_00.png"),
      toUrl("jr_pup_clean_normal_neutral_sleep_01.png"),
      toUrl("jr_pup_clean_normal_neutral_sleep_02.png"),
      toUrl("jr_pup_clean_normal_neutral_sleep_03.png"),
      toUrl("jr_pup_clean_normal_neutral_sleep_04.png"),
      toUrl("jr_pup_clean_normal_neutral_sleep_05.png"),
    ],
  },
  {
    stage: "pup",
    name: "stay",
    urls: [
      toUrl("jr_pup_clean_normal_neutral_stay_00.png"),
      toUrl("jr_pup_clean_normal_neutral_stay_01.png"),
      toUrl("jr_pup_clean_normal_neutral_stay_02.png"),
      toUrl("jr_pup_clean_normal_neutral_stay_03.png"),
    ],
  },
  {
    stage: "pup",
    name: "walk",
    urls: [
      toUrl("jr_pup_clean_normal_neutral_walk_00.png"),
      toUrl("jr_pup_clean_normal_neutral_walk_01.png"),
      toUrl("jr_pup_clean_normal_neutral_walk_02.png"),
      toUrl("jr_pup_clean_normal_neutral_walk_03.png"),
      toUrl("jr_pup_clean_normal_neutral_walk_04.png"),
      toUrl("jr_pup_clean_normal_neutral_walk_05.png"),
      toUrl("jr_pup_clean_normal_neutral_walk_06.png"),
      toUrl("jr_pup_clean_normal_neutral_walk_07.png"),
    ],
  },
  {
    stage: "adult",
    name: "bark",
    urls: [
      toUrl("jr_adult_clean_normal_neutral_bark_00.png"),
      toUrl("jr_adult_clean_normal_neutral_bark_01.png"),
      toUrl("jr_adult_clean_normal_neutral_bark_02.png"),
      toUrl("jr_adult_clean_normal_neutral_bark_03.png"),
    ],
  },
  {
    stage: "adult",
    name: "idle",
    urls: [
      toUrl("jr_adult_clean_normal_neutral_idle_00.png"),
      toUrl("jr_adult_clean_normal_neutral_idle_01.png"),
      toUrl("jr_adult_clean_normal_neutral_idle_02.png"),
      toUrl("jr_adult_clean_normal_neutral_idle_03.png"),
      toUrl("jr_adult_clean_normal_neutral_idle_04.png"),
      toUrl("jr_adult_clean_normal_neutral_idle_05.png"),
    ],
  },
  {
    stage: "adult",
    name: "scratch",
    urls: [
      toUrl("jr_adult_clean_normal_neutral_scratch_00.png"),
      toUrl("jr_adult_clean_normal_neutral_scratch_01.png"),
      toUrl("jr_adult_clean_normal_neutral_scratch_02.png"),
      toUrl("jr_adult_clean_normal_neutral_scratch_03.png"),
      toUrl("jr_adult_clean_normal_neutral_scratch_04.png"),
      toUrl("jr_adult_clean_normal_neutral_scratch_05.png"),
    ],
  },
  {
    stage: "adult",
    name: "shake",
    urls: [
      toUrl("jr_adult_clean_normal_neutral_shake_00.png"),
      toUrl("jr_adult_clean_normal_neutral_shake_01.png"),
      toUrl("jr_adult_clean_normal_neutral_shake_02.png"),
      toUrl("jr_adult_clean_normal_neutral_shake_03.png"),
      toUrl("jr_adult_clean_normal_neutral_shake_04.png"),
      toUrl("jr_adult_clean_normal_neutral_shake_05.png"),
    ],
  },
  {
    stage: "adult",
    name: "sit",
    urls: [
      toUrl("jr_adult_clean_normal_neutral_sit_00.png"),
      toUrl("jr_adult_clean_normal_neutral_sit_01.png"),
      toUrl("jr_adult_clean_normal_neutral_sit_02.png"),
      toUrl("jr_adult_clean_normal_neutral_sit_03.png"),
    ],
  },
  {
    stage: "adult",
    name: "sleep",
    urls: [
      toUrl("jr_adult_clean_normal_neutral_sleep_00.png"),
      toUrl("jr_adult_clean_normal_neutral_sleep_01.png"),
      toUrl("jr_adult_clean_normal_neutral_sleep_02.png"),
      toUrl("jr_adult_clean_normal_neutral_sleep_03.png"),
      toUrl("jr_adult_clean_normal_neutral_sleep_04.png"),
      toUrl("jr_adult_clean_normal_neutral_sleep_05.png"),
    ],
  },
  {
    stage: "adult",
    name: "stay",
    urls: [
      toUrl("jr_adult_clean_normal_neutral_stay_00.png"),
      toUrl("jr_adult_clean_normal_neutral_stay_01.png"),
      toUrl("jr_adult_clean_normal_neutral_stay_02.png"),
      toUrl("jr_adult_clean_normal_neutral_stay_03.png"),
    ],
  },
  {
    stage: "adult",
    name: "walk",
    urls: [
      toUrl("jr_adult_clean_normal_neutral_walk_00.png"),
      toUrl("jr_adult_clean_normal_neutral_walk_01.png"),
      toUrl("jr_adult_clean_normal_neutral_walk_02.png"),
      toUrl("jr_adult_clean_normal_neutral_walk_03.png"),
      toUrl("jr_adult_clean_normal_neutral_walk_04.png"),
      toUrl("jr_adult_clean_normal_neutral_walk_05.png"),
      toUrl("jr_adult_clean_normal_neutral_walk_06.png"),
      toUrl("jr_adult_clean_normal_neutral_walk_07.png"),
    ],
  },
  {
    stage: "senior",
    name: "bark",
    urls: [
      toUrl("jr_senior_clean_normal_neutral_bark_00.png"),
      toUrl("jr_senior_clean_normal_neutral_bark_01.png"),
      toUrl("jr_senior_clean_normal_neutral_bark_02.png"),
      toUrl("jr_senior_clean_normal_neutral_bark_03.png"),
    ],
  },
  {
    stage: "senior",
    name: "idle",
    urls: [
      toUrl("jr_senior_clean_normal_neutral_idle_00.png"),
      toUrl("jr_senior_clean_normal_neutral_idle_01.png"),
      toUrl("jr_senior_clean_normal_neutral_idle_02.png"),
      toUrl("jr_senior_clean_normal_neutral_idle_03.png"),
      toUrl("jr_senior_clean_normal_neutral_idle_04.png"),
      toUrl("jr_senior_clean_normal_neutral_idle_05.png"),
    ],
  },
  {
    stage: "senior",
    name: "scratch",
    urls: [
      toUrl("jr_senior_clean_normal_neutral_scratch_00.png"),
      toUrl("jr_senior_clean_normal_neutral_scratch_01.png"),
      toUrl("jr_senior_clean_normal_neutral_scratch_02.png"),
      toUrl("jr_senior_clean_normal_neutral_scratch_03.png"),
      toUrl("jr_senior_clean_normal_neutral_scratch_04.png"),
      toUrl("jr_senior_clean_normal_neutral_scratch_05.png"),
    ],
  },
  {
    stage: "senior",
    name: "shake",
    urls: [
      toUrl("jr_senior_clean_normal_neutral_shake_00.png"),
      toUrl("jr_senior_clean_normal_neutral_shake_01.png"),
      toUrl("jr_senior_clean_normal_neutral_shake_02.png"),
      toUrl("jr_senior_clean_normal_neutral_shake_03.png"),
      toUrl("jr_senior_clean_normal_neutral_shake_04.png"),
      toUrl("jr_senior_clean_normal_neutral_shake_05.png"),
    ],
  },
  {
    stage: "senior",
    name: "sit",
    urls: [
      toUrl("jr_senior_clean_normal_neutral_sit_00.png"),
      toUrl("jr_senior_clean_normal_neutral_sit_01.png"),
      toUrl("jr_senior_clean_normal_neutral_sit_02.png"),
      toUrl("jr_senior_clean_normal_neutral_sit_03.png"),
    ],
  },
  {
    stage: "senior",
    name: "sleep",
    urls: [
      toUrl("jr_senior_clean_normal_neutral_sleep_00.png"),
      toUrl("jr_senior_clean_normal_neutral_sleep_01.png"),
      toUrl("jr_senior_clean_normal_neutral_sleep_02.png"),
      toUrl("jr_senior_clean_normal_neutral_sleep_03.png"),
      toUrl("jr_senior_clean_normal_neutral_sleep_04.png"),
      toUrl("jr_senior_clean_normal_neutral_sleep_05.png"),
    ],
  },
  {
    stage: "senior",
    name: "stay",
    urls: [
      toUrl("jr_senior_clean_normal_neutral_stay_00.png"),
      toUrl("jr_senior_clean_normal_neutral_stay_01.png"),
      toUrl("jr_senior_clean_normal_neutral_stay_02.png"),
      toUrl("jr_senior_clean_normal_neutral_stay_03.png"),
    ],
  },
  {
    stage: "senior",
    name: "walk",
    urls: [
      toUrl("jr_senior_clean_normal_neutral_walk_00.png"),
      toUrl("jr_senior_clean_normal_neutral_walk_01.png"),
      toUrl("jr_senior_clean_normal_neutral_walk_02.png"),
      toUrl("jr_senior_clean_normal_neutral_walk_03.png"),
      toUrl("jr_senior_clean_normal_neutral_walk_04.png"),
      toUrl("jr_senior_clean_normal_neutral_walk_05.png"),
      toUrl("jr_senior_clean_normal_neutral_walk_06.png"),
      toUrl("jr_senior_clean_normal_neutral_walk_07.png"),
    ],
  },
];

export const JACK_RUSSELL_ANIMATION_NAMES = [
  "bark",
  "idle",
  "scratch",
  "shake",
  "sit",
  "sleep",
  "stay",
  "walk",
];

