/** @format */

// src/utils/dogSpritePaths.js
// Sprite asset path helpers for static renders and Pixi sheets.

import { withBaseUrl } from "@/utils/assetUrl.js";

export const DOG_STAGE_IDS = Object.freeze(["PUPPY", "ADULT", "SENIOR"]);
export const DOG_STAGE_SHORT = Object.freeze(["pup", "adult", "senior"]);
export const DOG_CONDITION_IDS = Object.freeze([
  "clean",
  "dirty",
  "fleas",
  "mange",
]);

const DEFAULT_SPRITE_DIR = "/assets/sprites";
const DEFAULT_ATLAS_DIR = "/assets/atlas";

const DEFAULT_STATIC_SPRITE = "/assets/imports/jr/idle/frame_000.png";

export const DOG_STAGE_LABEL_BY_STAGE_ID = Object.freeze({
  PUPPY: "Puppy",
  ADULT: "Adult",
  SENIOR: "Senior",
});

export function normalizeDogStageId(stageLike) {
  const s = String(stageLike || "PUPPY")
    .trim()
    .toLowerCase();

  if (s.startsWith("adult") || s.includes("adult")) return "ADULT";
  if (s.startsWith("sen") || s.includes("senior")) return "SENIOR";

  // Accept `pup`, `puppy`, legacy stage strings
  return "PUPPY";
}

export function normalizeDogStageShort(stageLike) {
  const id = normalizeDogStageId(stageLike);
  if (id === "ADULT") return "adult";
  if (id === "SENIOR") return "senior";
  return "pup";
}

/**
 * Normalize cleanliness to a render condition key.
 * Accepts both tier IDs (FRESH/DIRTY/FLEAS/MANGE) and condition strings.
 */
export function normalizeDogCondition(conditionLike) {
  const c = String(conditionLike || "clean")
    .trim()
    .toLowerCase();

  if (c === "dirty" || c === "dirt") return "dirty";
  if (c === "fleas" || c === "flea") return "fleas";
  if (c === "mange") return "mange";

  // Tier IDs
  if (c === "dir" || c === "dirty" || c === "tier_dirty") return "dirty";
  if (c === "fleas" || c === "tier_fleas") return "fleas";
  if (c === "mange" || c === "tier_mange") return "mange";

  // Treat "fresh" as clean
  return "clean";
}

export function normalizeDogConditionId(conditionLike) {
  const key = normalizeDogCondition(conditionLike);
  return DOG_CONDITION_IDS.includes(key) ? key : "clean";
}

export function getDogStageLabel(stageLike) {
  const id = normalizeDogStageId(stageLike);
  return DOG_STAGE_LABEL_BY_STAGE_ID[id] || "Puppy";
}

/**
 * Static fallback sprite used while strips load (or if strips fail).
 */
export function getDogStaticSpriteUrl(_stageLike) {
  return withBaseUrl(DEFAULT_STATIC_SPRITE);
}

/**
 * Pixi sheet path: /assets/sprites/jr/<stage>_<condition>.png
 */
export function getDogPixiSheetUrl(_stageLike, _conditionLike) {
  const stage = normalizeDogStageShort(_stageLike);
  const condition = normalizeDogConditionId(_conditionLike);
  return withBaseUrl(`${DEFAULT_SPRITE_DIR}/jr/${stage}_${condition}.png`);
}

/**
 * Atlas helpers (generated by scripts/generate-sprites.js).
 * Files live in /public/assets/atlas as jr_<stage>.json/png by default.
 */
export function getDogAtlasJsonUrl(stageLike, baseDir = DEFAULT_ATLAS_DIR) {
  const stage = normalizeDogStageShort(stageLike);
  return withBaseUrl(`${baseDir}/jr_${stage}.json`);
}

export function getDogAtlasImageUrl(stageLike, baseDir = DEFAULT_ATLAS_DIR) {
  const stage = normalizeDogStageShort(stageLike);
  return withBaseUrl(`${baseDir}/jr_${stage}.png`);
}

export function getDogAtlasUrls(stageLike, baseDir = DEFAULT_ATLAS_DIR) {
  return {
    jsonUrl: getDogAtlasJsonUrl(stageLike, baseDir),
    imageUrl: getDogAtlasImageUrl(stageLike, baseDir),
  };
}
