//src/animation/dogAnimationMap.js

// Canonical animation routing map for AI states, moods, and runtime behavior
// actions emitted by the simulation and Redux layers.
export const DOG_ANIMATIONS = Object.freeze({
  // Canonical manifest keys
  idle: "idle",
  walk: "walk",
  walk_left: "walk_left",
  walk_right: "walk_right",
  turn_walk_left: "turn_walk_left",
  turn_walk_right: "turn_walk_right",
  bark: "bark",
  scratch: "scratch",
  sleep: "sleep",
  sit: "sit",
  wag: "wag",
  eat: "eat",
  lay_down: "lay_down",
  jump: "jump",
  spin: "spin",
  wave: "wave",
  fetch: "fetch",
  bow: "bow",
  beg: "beg",
  roll_over: "roll_over",
  play_dead: "play_dead",
  stay: "stay",
  paw: "paw",
  shake: "shake",
  highfive: "highfive",
  crawl: "crawl",
  dance: "dance",
  point_position: "point_position",
  territorial_bark: "territorial_bark",
  gate_watch: "gate_watch",
  limping: "limping",
  shivering: "shivering",
  lethargic_lay: "lethargic_lay",
  idle_resting: "idle_resting",
  light_sleep: "light_sleep",
  deep_rem_sleep: "deep_rem_sleep",
  drink: "drink",
  sniff: "sniff",
  thrashing: "thrashing",

  // AI behavior states
  dig: "scratch",
  digging: "scratch",
  running: "walk",
  walking: "walk",
  chase: "walk",
  chasing: "walk",
  wander: "walk",
  exploring: "walk",

  // Mood/state hints
  ok: "idle",
  calm: "idle",
  content: "idle",
  happy: "wag",
  excited: "walk",
  restless: "walk",
  hungry: "beg",
  sleepy: "light_sleep",
  tired: "light_sleep",
  dirty: "scratch",
  sad: "idle_resting",
  stressed: "shivering",
  fragile: "lethargic_lay",

  // Care + interaction actions
  feed: "eat",
  feed_quick: "eat",
  feed_premium_empty: "sniff",
  feed_premium_cooldown: "sniff",
  feed_rejected_hard: "sniff",
  sniff_kibble_reject: "sniff",
  water: "drink",
  play: "walk",
  pet: "wag",
  pet_cuddle: "wag",
  pet_side_eye: "idle",
  pet_doze_off: "light_sleep",
  pet_zoomies: "walk",
  zoomies: "walk",
  rest: "idle_resting",
  nap: "light_sleep",
  bathe: "shake",
  potty: "sniff",
  potty_fakeout: "sniff",
  scoop: "idle",
  wake: "idle",
  sleep_auto: "light_sleep",
  dream_woof: "deep_rem_sleep",

  // Training and trick outcomes
  train: "sit",
  train_perfect: "sit",
  train_doze_off: "light_sleep",
  train_zoomies: "walk",
  train_ignore: "idle",
  train_reinterpret: "sit",
  trainblocked: "sit",
  trainfailed: "sit",
  trainlocked: "stay",

  // Surprise / heist / story actions
  button_heist: "fetch",
  surprise_cleanup: "sit",
  surprise_fetch_cleanup: "fetch",
  surprise_fetch_recover: "fetch",
  guilty_paws: "paw",
  accident: "shivering",
  table_theft: "fetch",
  destructive_chewing: "fetch",
  equip_toy: "wag",
  treasure_found: "sniff",
  session_start: "idle",

  // Lifecycle / meta states
  rescued: "shivering",
  farewell: "idle_resting",
  runaway_strike: "walk",
  runaway_returned: "walk",
  vacation_on: "idle_resting",
  vacation_off: "wag",
});
