Catfishfishcat10101
doggerz

Type / to search
Code
Issues
Pull requests
2
Discussions
Actions
Projects
Wiki
Security
7
Insights
Settings
Deploy Vite to GitHub Pages
Update vite.config.js #25
Jobs
Run details
Triggered via push 10 minutes ago
@Catfishfishcat10101Catfishfishcat10101
pushed
 a176b83
main
Status
Failure
Total duration
1m 36s
Artifacts
–


Annotations
1 error
build
Process completed with exit code 1.